namespace SpriteKind {
    export const Dialogue = SpriteKind.create()
    export const Background = SpriteKind.create()
}
sprites.onCreated(SpriteKind.Enemy, function (sprite) {
    sprite.follow(player_1, 30)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestOpen, function (sprite5, location2) {
    if (controller.A.isPressed()) {
        if (current_zone == "mz_1") {
            on_dialogue = true
            story.startCutscene(function () {
                story.spriteSayText(player_1, "Already open. . .", 1, 15, story.TextSpeed.Slow)
                story.spriteSayText(player_1, "Obviously.", 1, 15, story.TextSpeed.Slow)
                story.spriteSayText(player_1, "God forbid I find something useful.", 1, 15, story.TextSpeed.Slow)
                story.cancelAllCutscenes()
                on_dialogue = false
            })
        }
    }
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    y_direction = -200
    x_direction = 0
    animation.runImageAnimation(
    player_1,
    assets.animation`walk_up_animation`,
    200,
    true
    )
})
function initialize_menu () {
    list = [0, 1]
    menu_opt_one = sprites.create(img`
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffcbdddddbfffffffffbdddddbbbbffffffcddddbbbcfffffffffbddddddbfffffffffdddddbbbbcffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffb1111111dcfffffffd11111111dffffffc1111111dbffffffffb1111111dcfffffffd11111111bffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffb111111111cffffffd11111111dffffffc111111111bfffffffd11111111dcffffffd11111111dffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffc111dccd11dffffffcccb11bcccfffffffb11dccb11dfffffffcd11cccd11bffffffcccd11bcccffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffbdddbcfffffffffffc11dfffc11dfffffffffc11bffffffffffc11dfffb11bfffffffb11cffc11dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffcd111111cffffffffffc11bffffbddfffffffffc11bffffffffffc11dfffc11bfffffffb11cfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffb11111111cfffffffffc11bffffffffffffffffc11bffffffffffc11dfffc11bfffffffb11cfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffbd11111111dfffffffffc11bffffffffffffffffc11bffffffffffc11dfffc11bfffffffb11cffb11bfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffbb11dbbbbbbbcfffffffffd11bcccffffffffffffc11bfffffffffcd111ddbb11bffffffb111ddd111cfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffdb11d1111111bfffffffffb11d111dbffffffffffc11bfffffffffc1111111111bffffffd11111111bffffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffdb11d1111111bffffffffffbdd11111bfffffffffc11bfffffffffcd111111111bffffffb11111111dcfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffff1b11dd11111dcffffffffffffcccbd1dfffffffffc11bffffffffffc11dcccd11bffffffcd11bccd11bfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffdb111ddddddbfffffffffffffffffd11cffffffffc11bffffffffffc11dfffb11bfffffffb11cfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffbdd1111dddddffffffffffbbcffffb11cffffffffc11bffffffffffc11dfffc11bfffffffb11bfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffbbddddddddbffffffffffd1dffffd1dfffffffffc11bffffffffffc11dfffc11bfffffffb11bfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffd11bccb11dfffffffffc11bffffffffffc11dfffc11bfffffffb11cfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffc11111111cfffffffffc11bffffffffffc11dfffc11bfffffffb11cfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffc11111dbffffffffffc11bffffffffffc11dfffc11bfffffffb11cfffd1dfffffffffb11cfffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffcbbbbcfffffffffffcbdcffffffffffcbbbfffcbbcfffffffcbbcfffbbbfffffffffcdbcfffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffffcccfffffffccccccfffffffffcccccfffffffffffffccccccffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1dcffffffd1dffffffc111111dbfffffffc111dcffffffffffffd11111ddcfffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb11dffffffd1dffffffc11111111dffffffc1111cffffffffffffd11111111bffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb111bfffffd1dffffffcd11dcbd11bfffffc1111cffffffffffffb111dbd111cfffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dfffffd1dfffffffc11bfffd1dffffffc111cfffffffffffffb11cffc11dfffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dfffffd1dfffffffc11bfffbddffffffc111cfffffffffffffb11cfffd1dfffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dfffffd1dfffffffc11bffffffffffffc11dcfffffffffffffb11cfffb1dfffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dfffffd1dfffffffc11bffffffffffffc111cfffffffffffffb11bfffd1dfffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dcffccd1dffffffcb11bccccffffffffc111cffffffffffffcd11bccd11bfffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb11111111111dffffffc11111111cfffffffc111cffffffffffffd111111111cfffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb11111111111dffffffc11111111cfffffffc111cffffffffffffd1111111dcffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb11d1dddd1d1dffffffcd11dbcccffffffffc11dfffffffffffffd111dddbcfffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dffffcd1dfffffffc11bffffffffffffc111ffffffffffffffd11cfffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dfffffd1dfffffffc11bffffffffffffc111ffffffffffffffb11cfffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcd1bfffff11dfffffffc11bfffbddfffffffd11cfffffffffffffb11cfffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dfffffd1dfffffffc11bffc11dfffffffb11dcffffffffffffb11cfffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11bfffffd1dffffffcd11dbb111bfffffffc1111dddddcffffffb11cfffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11dfffffd1dffffffc11111111dfffffffffb11111111cffffffb11cfffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcd1dfffffd1dffffffc111111dbfffffffffffcd111111cffffffb11cfffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfffffcccfffffffccccccfffffffffffffffccccccfffffffcccffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        `, SpriteKind.Player)
    menu_opt_two = sprites.create(img`
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffcccccccfffffffffcccccccccfffffffccccccffffffffffcccbbcccffffffffcccccccccfffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffd111111dcffffffcd11111111cfffffc1111111bffffffffb111111dbfffffffd11111111bffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffd1111111dcfffffc111111111cfffffc11111111dfffffffb11111111bffffffd11111111bffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffd111bbd11dffffffbbb11dbccfffffffb11dbbd11cffffffcd11bcb111ffffffbbbd11bcccffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffb11cffc11dfffffffffd1dffffffffffc11bffc11dfffffffb11cffb11cffffffffb11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffd11ffffbddfffffffffd1dffffffffffc11bfffd1dfffffffb11cffc11bffffffffb11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffd1dffffffffffffffffd1dffffffffffc11bfffd1dfffffffb11cffc11bffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffb11cfffffffffffffffd1dffffffffffb11bfffb1dfffffffb11cfcd11cffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffb11dccccfffffffffffd1dfffffffffc111ddbbd1dffffffb111ddd11dfffffffffb11cfffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffd11111dbffffffffffd1dfffffffffc111111111dffffffb11111111cfffffffffc11cfffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffcbd11111bfffffffffd1dfffffffffcd111dd111dffffffb111dd111bfffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffcccd1dfffffffffd1dffffffffffc11bffb11dfffffffb11cfcd11cffffffffc11cfffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1dcffffffffd1dffffffffffc11bfffd1dfffffffb11cffc11bffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffcddffffb11fffffffffd1dffffffffffc11bfffd1dfffffffb11cffc11bffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffb11cfffd1dfffffffffd1dffffffffffc11bfffd1dfffffffb11cffc11bffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffc111bbd11bfffffffffd11ffffffffffc11bfffd1dfffffffb11cffc11bffffffffc11cfffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffc111111dffffffffffd1dffffffffffc11bfffd1dfffffffb11cffc11bffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffcd111bcffffffffffb1dffffffffffc11bfffd1dfffffffb11cffc11bffffffffc11cfffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffcccfffffffffffccffffcccfffffffcccffffccffffffffffccffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbcfffffffbdcfffffcdddddbbffffffffddddcffffffffffffdddbbbcffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffc11bffffffd1cfffffc1111111dcffffffd111bffffffffffff1111111dcffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffc111cfffff11cfffffc1111dd11dffffffd111bffffffffffffd111d111dcfffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffccffffffffffffffffffffb11bfffff11cffffffc11bffc11bfffffcd11bffffffffffffc11dcfc11dfffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffbd1dbcfffffffffffffffffff11dffffc11cffffffc11bfffddbffffffd11bfffffffffffff11dfffb1dfffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffd111111bffffffffffffffffff11dffffc11cffffffc11bffffffffffffd11bfffffffffffff11dfffc1dfffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffb11111111bfffffffffffffffff11dffffc11bffffffc11bffffffffffffb11bfffffffffffff11dfffb1dfffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffbb1111ddd1dffffffffffffffffcd1dffffc11bffffffc11bffffffffffffb11bffffffffffffc11dccb11dfffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffcdd11bddddddcffffffffffffffcd111ddddd11cfffffc1111ddddffffffffd11bffffffffffffd1111d111cfffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffc1d11d111111bffffffffffffffc11111111111cfffffc11111111ffffffffb11bffffffffffff11111111bffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffc1d11d111111cffffffffffffffc1111dddd111cffffffd11dbcccffffffffb11cffffffffffffd111ddbcfffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffc1d11ddd11dbffffffffffffffffc11dffffc11cffffffc11bffffffffffffb11cffffffffffffc11dfffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffc1d111ddbbddfffffffffffffffff11bffffcd1cffffffc11bffffccffffffb11cffffffffffffc11dfffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffbd11111111bfffffffffffffffffd1bffffcd1cffffffc11bfffdddffffffb11bfffffffffffff11dfffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffccccccccccfffffffffffffffff11bffffc11cffffffc11bffb11bffffffc111bcccccffffffc11dfffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11bffffc11cffffff1111dd111cfffffffb111111ddcffffff11dfffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11dffffc11cfffffc11111111bfffffffffb1111111cffffff11dfffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddbffffcddcffffffddddddbcfffffffffffbddddddcffffffddbfffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        `, SpriteKind.Player)
    menu_help = sprites.create(img`
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffcbbcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11ffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffcd1111dbfffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffff11fff11fff11ffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffff
        ffffffcd11111ddcffffffdddbffffffffffffffffffffffdfffffffffffcfffcfffffffffffffffff11ffff11ffff1ffffffcfffffffffffffffdcffffffffffffffffcffffffffffffffffffffffff
        fffffcb111dbddddcfffff1ccdcffffffffffffffffffffc1cfffffffffc1cfcdfffffffffffffffff1ffff1111ffff1fffffdcffffffffffffffdbfffffffffffffffcdffffffffffffffffffffffff
        ffffcdd11dd11111dfffff1ffdbbbdbcdddccdbcfddbffff1bdbfcdfcdcd1dcd1bccdddfcbbdbfffff1ffff1ff1ffff1ffffb1dcfbddcffffddbfdbddcfcddbffbddccd1bfffffffffffffffffffffff
        ffffbdd11d1111111cffff1cb1cb1cfbbfdcdbffcdfffffc1bf1cc1fcdcf1cfcdffdcfdbcdcc1cffff1fff11ff1ffff1fffff1cfbdfbdfffcdfffddfbdf1cfdcbdfcdfcdffffffffffffffffffffffff
        ffffbdd11d1111111cffff1bbcfbdffdbbdfcdbcfddcfffc1cfdbcdfc1fc1ffcdff1ffbbcdff1cffff1fff1ffff1fff1fffffdcfdbfcdffffddcfdbfbdcdcfdbbbfc1fbdffffffffffffffffffffffff
        ffffbdd11b111111dcffff1ffffcdffddcfffcdbffb1ffff1ffdcc1fc1cf1cfcdff1cfdbcdff1cffff1ff1111111fff1fffff1cfdbfcdfffffb1cdcfcdc1cfdbbbfcdfbdffffffffffffffffffffffff
        ffffbdd11db1111dcfffff1ffffbdffbdcbfbbdbcbb1fffc1cbdcc1bddccdbccdcfbdbdccdffdcffff1ff11ffff11ff1fffffdbccdbdbfffcbbdcbcfbdfdbbdccdbdbfcdccdbffffffffffffffffffff
        ffffcdd111ddbdddcfffffbffffccfffbbcfcbbfcbbcffffcbbcffbbcccfcbcfbbcfbbcffcffcfffff11f1ffffff1f11fffffcbcfcbcffffccbcfccfccfcbbcffcbbfffbbcccffffffffffffffffffff
        fffffbb111111111cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11ffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111ffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111fff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffcbddbcffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffff11ffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffcd11111bffffffbddbffffffffffffffffffffffcdfffffffffffffffffffffffffffffffff11fffffffff11ffffffffffffffffffffffffffbcfffffffffffffffcbffffffffffffffffffff
        fffffffd1111111bfffffdbcddfffffffffffffffffffffcdffffffffffcdffcdfffffffffffffffff1fff11111fff11ffffccfffffffffffffffffffdcfffffffffffffffcdffffffffffffffffffff
        fffffcb11111111dcffffdbfcdcbcdccddbfbddfcddcfffcdbdcfbcfcbcd1dbd1bfcddbfccbdbfffff1fff1fffb1fff1fffcdbcffccfffffcccffcccfdcffcccfffcccfffcbdffffffffffffffffffff
        fffffdb11bbbbbbbcffffdbcdbcddccdccdcdcffdbfffffc1ccdcdbfbbfbdffbdcfdccdcbdbcdfffff1fff1fffbbfff1fffbddccdbddffffdddcbbbdfdcfbdbdcfbdbdccdbbdffffffffffffffffffff
        ffffcdb11b111111dffffddbbffdbfcdcbbfbdcfbdbffffcdffdcdbfbbfcdffcdfcdcfdbcdffdfffff1fff11111bfff1ffffdbfcdfc1cfffdbfcdccdfdcfdbfbdcdff1cbdfcdffffffffffffffffffff
        ffffc1b11b111111dffffdbffffdcfbdbcfffcdcfcdbfffcdfcdcdbfbbfcdffcdfcdcfdbcdffdcffff1fff1ffff1fff1ffffbbfbdffdcfffdcfc1ddcfdcfdcfbdbdfcdcbbfcdffffffffffffffffffff
        ffffc1b11dd11111cffffdbffffdcfcdccccccdcbcbbfffcdcbbfbbcddfcdcfcdcfdbcdccdffdcffff1fff1ffffbfff1ffffdbfcdfcdcfffdbfcdcfffdcfdbfbbbdfc1cbdfbdcfcfffffffffffffffff
        ffffcdb111dddbddcffffbcffffbcffcdbccbdbfcbbffffcbbbffcbbfbffbbcfbbfcbbcfcbffbfffff1fff1bbbb1ff11ffffbdbcdddbffffdcffbdbbfbdccdbdffdbbdccdbbdcbdfffffffffffffffff
        fffffbb111111111cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffbbbbbfff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffcbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffff11fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffbffffcbfffffffffffffffffffbfffffffffccfccfffffffffcbfffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffff
        ffffffffffffffffffffddffffffffffffffbcfffcdffffffffffffffffffcdfffffffffdbfbbfffffffffcbfffffffffffffccffffffffffffffffffffffffffffffffffbcfffffffffffffffffffff
        fffffffffffffffffffcd1cfffffcffcccffcfffccdfffffcccffffccfffcc1fffffcccfdbffffffccfccffcffffcfffcccffbdcffccffffffccffffcffffccffffcffcffcfffccfffccffffffffffff
        fffffffffffffffffffbbdbffdffdccdbdbfdcfddbdffffcdbdccddddcfbdbdffffcdbdfdbfbbfdbdddb1fcdfbbdddfcdbdbcddbfbbbbffffdbdbcdbddfcdbdcbdddddddfbcfbbbdcdbbffffffffffff
        fffffffffffffffffffdccdffdff1cdbfbdcdccdfcdffffdcfdbf1bfdccdfcdffffdccdcdbfbbfddfdbfdccdfb1cc1fdbfbbfbbfc1fcdfffcdfbbc1cc1cbdfdbc1cc1cc1fdcc1ccdc1cfffffffffffff
        ffffffffffffffffffc1dd1ccdff1cdbfcdfdcbdfcdffff1cfdbfdcfdcbdfcdffff1bdbfdcfbbfdcfdcfdccdfcdfc1c1cfbbfbbfc1ddcfffbdddccdcf1cddddfcdfc1fcdfdcc1ddcfbddffffffffffff
        ffffffffffffffffffdbccdbcdfcdfddfbdfdcbdfb1ffffdcf1bfdcfdcbdfc1ffff1ccffdbfbbfdcfdcfdccdfcdfc1f1cfddfbbfc1cfffffbdcffc1ffdcbdcffcdfc1fcdfdcc1cffffcdcfcfffffffff
        ffffffffffffffffffdcffcdcdbdbfcdbdcfdbcdbbdcfffbdbbdfdcfdccdbbdcfffbdbbfbdcbdfdcfdcfdccdccdfcdfbdbbdfcdbfdbbbfffcdbbccdffdccdbbccdfcdfcdfbdfddbbcdbdcbdfffffffff
        ffffffffffffffffffffffffffcfffffcffffcffcfffffffcfffffffffffcfffffffccfffcffcffffffffffcfffffcffccfffffcffccffffffccfffffffffccfffffcfffffcffccffccfffcfffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffcbbccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbddbfffbdddfffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffcd11111cfffffffffffffffffffffffffffffffffffccffffffffffcffffffffffffffffffffffffffffffffffddd1dbfbd1d1dffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffb1111111cfffdcffdcfffffffffffffffffffffffffdcfffffffffcdffffffffffffffffffffffffffffffcfffdd1dddcbd1d11ffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffcb111ddd1ddcffbbfbdffffffffffffffffffffffffffdcfffffffffcdffffffffffffffffffffffffffffcddcff11d11dddd11ddffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffbb11bddbbbbbffcdcdcfdddcfdcfbcffffbddcfbcddcfdcfbcfbbfffc1bdbffbbdbfbcfcbfbddbfffcdfbbbbdcff1d111d1111d11ffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffcdb11b1111d1dfffb1dfbdfc1cdcfdbfffcdfcdcddfbdfdcfdcfbbfffc1ccdcbdfbdfdbfbdcdfcdffffdbdcffdcffd11dd111dd11dffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffcdb11b111111dfffcdcfbbfc1c1cfdbfffbdfcdcbbfcbfdcfdbfbbfffcdffdcdbfcdfdbfbdcdbdbffffc1bffcdcffd1d11d1111dddffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffcdb11bd11111bffffdcfbdfcdcdcfdbfffbdfcdcbbfcdfdcfdbfdbfffcdffdcdbfbdfdbfdbcdbcfffffdbdfffdcffccddd1dd1d1bcffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffcdb111dddddbcffffdcfcdbdbfdbbdbfffcdbbbfbbfcbfdbfddbddfffcdffdcbdbddfbdbdff1bbbfffbdfdbffdcfffcddd1d1dddcfffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffbb11111d1d1cffffcfffcbcffcbcfcffffcbcffccfccfcbfcbccdffffcffcffcbccffbbcffcbccfffccfccffcffffffbd11d1bfffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffcbdddddddbffffffffffffffffffffffffffffffffffffffccbdffffffffffffffffffffffffffffffffffffffffffcbd1dbcfffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffbdbcffffffffffffffffffffffffffffffffffffffffffffd1dcffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffffcccffffffffffffffffcbffffbcfffffffffffcbfffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffcdbdbfffffffffffffffcdffffdcfffffffffffbdffffcdcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffdbfffffcbbfffbbcffcbbdffffdcfccfccffbbcbdcbcfc1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffdcffffcdcdbfbbbdccdbbdffffdcfdcfbbfbdbcb1bbdfc1ffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        fffffffffffffffffffcdcffbfbbfcdcdcfdbbdfcdffffdcfdcfbbcdcffbdfbdfcdfffffb11dcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffdcffdcdbfcdcdffdbbbfcdffffdcfdcfbbc1cffcdb1cffbffffb11dddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1111111ffffffff
        ffffffffffffffffffffdbfc1cbdfbdcdcfdcbdfbdcfffdcfdbfdbcdcffbdcdcffcffffb1ddddcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111fff111fffffff
        ffffffffffffffffffffcddbdccbddcfcddbffddbdcfffbdccdbcbfcddccdfbdfcdffffb1d111cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffff11ffffff
        ffffffffffffffffffffffccdffffffffffffffffffffffffffffffffffffffffffffffb11dddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffffff11fffff
        fffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffcccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fff11111fff11ffff
        fffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fff1fffb1ff11ffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffff1fffb1fff1ffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffff11111bfff1ffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffff1ffff1fff1ffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffff1ffffbfff1ffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fff1bbbbbff11ffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11ffbbbbbfff1fffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffff11fffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffff11ffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111111111fffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffcffffffffcffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbcffffffbfffffffcbfffccfffffffffffffffffffff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffbcbffbccbccbccbbcfbbccbffdcbbcbbbbbcbcbff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccbbfbffbcbbcbbfcbdffccbcbffbcbcbdbcbcbdcbff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbdbcbcffbbfbbbcbcbbcfcdcdbffbccccbbcbccbdbff
        fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        `, SpriteKind.Player)
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (info.score() < 10) {
        info.setScore(10)
        music.play(music.melodyPlayable(music.beamUp), music.PlaybackMode.UntilDone)
    }
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite3, otherSprite) {
    sprites.destroy(sprite3, effects.spray, 500)
    sprites.destroy(bullet, effects.none, 0)
    music.play(music.melodyPlayable(music.zapped), music.PlaybackMode.UntilDone)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (info.score() > 0) {
        bullet = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . 4 4 . . . . . . . 
            . . . . . . 4 5 5 4 . . . . . . 
            . . . . . . 2 5 5 2 . . . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, player_1, x_direction, y_direction)
        info.changeScoreBy(-1)
        music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.UntilDone)
    } else {
        music.play(music.melodyPlayable(music.bigCrash), music.PlaybackMode.UntilDone)
    }
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, player_1)
    player_1.setImage(assets.image`walk_down_1`)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    y_direction = 0
    x_direction = -200
    animation.runImageAnimation(
    player_1,
    assets.animation`WalkLeft`,
    200,
    true
    )
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, player_1)
    player_1.setImage(assets.image`walk_right_1`)
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, player_1)
    player_1.setImage(assets.image`walk_left_1`)
})
scene.onOverlapTile(SpriteKind.Player, tileUtil.door0, function (sprite2, location) {
    tileUtil.loadConnectedMap(MapConnectionKind.Door1)
    tiles.placeOnRandomTile(player_1, tileUtil.door0)
    if (tileUtil.currentTilemap() == map_zone_2) {
        info.startCountdown(300)
        player_1.x = 26
    } else {
        player_1.x = 231
    }
})
info.onCountdownEnd(function () {
    game.gameOver(true)
    game.setGameOverEffect(true, effects.slash)
    game.setGameOverMessage(true, "YOU SURVIVED")
    music.stopAllSounds()
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    y_direction = 0
    x_direction = 200
    animation.runImageAnimation(
    player_1,
    assets.animation`WalkRight`,
    200,
    true
    )
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, player_1)
    player_1.setImage(assets.image`walk_up_1`)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    y_direction = 200
    x_direction = 0
    animation.runImageAnimation(
    player_1,
    assets.animation`walk_down_animation`,
    200,
    true
    )
})
info.onLifeZero(function () {
    music.stopAllSounds()
    game.gameOver(false)
    music.play(music.stringPlayable("G F G A - F E D ", 120), music.PlaybackMode.UntilDone)
    game.setGameOverMessage(false, "YOU GOT CAUGHT!")
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite4, otherSprite2) {
    info.changeLifeBy(-1)
})
tileUtil.onMapLoaded(function (tilemap2) {
    if (tileUtil.currentTilemap() == map_zone_1) {
        tileUtil.coverAllTiles(tileUtil.door0, sprites.dungeon.doorOpenEast)
    } else {
        tileUtil.replaceAllTiles(tileUtil.door0, sprites.builtin.forestTiles10)
    }
})
let bullet: Sprite = null
let menu_help: Sprite = null
let menu_opt_two: Sprite = null
let menu_opt_one: Sprite = null
let list: number[] = []
let x_direction = 0
let y_direction = 0
let on_dialogue = false
let player_1: Sprite = null
let current_zone = ""
let map_zone_2: tiles.TileMapData = null
let map_zone_1: tiles.TileMapData = null
initialize_menu()
map_zone_1 = tilemap`mz_1`
map_zone_2 = tilemap`mz_2`
current_zone = "mz_1"
tiles.setCurrentTilemap(map_zone_1)
player_1 = sprites.create(assets.image`walk_1`, SpriteKind.Player)
info.setLife(1)
info.setScore(10)
on_dialogue = false
tileUtil.connectMaps(map_zone_1, map_zone_2, MapConnectionKind.Door1)
tiles.placeOnRandomTile(player_1, sprites.dungeon.collectibleInsignia)
let player_speed = 200
controller.moveSprite(player_1, 100, 100)
game.onUpdate(function () {
    if (on_dialogue) {
        controller.moveSprite(player_1, 0, 0)
        animation.stopAnimation(animation.AnimationTypes.All, player_1)
    } else {
        controller.moveSprite(player_1, 100, 100)
    }
})
game.onUpdateInterval(5000, function () {
    tileUtil.createSpritesOnTiles(sprites.dungeon.collectibleRedCrystal, assets.image`Ghost`, SpriteKind.Enemy)
    tileUtil.createSpritesOnTiles(sprites.dungeon.collectibleBlueCrystal, assets.image`Ghost`, SpriteKind.Enemy)
})
forever(function () {
    scene.centerCameraAt(0, 0)
    scene.cameraFollowSprite(player_1)
    music.play(music.stringPlayable("C5 A B G A F G E ", 147), music.PlaybackMode.UntilDone)
})
